In [1]:
# 데이타 시각화해야 하는 이유
# 아나피 비행 지도 그리기

In [2]:
import pandas as pd
import numpy as np
from datetime import datetime
from collections import OrderedDict
%matplotlib inline
import matplotlib.pyplot as plt

In [3]:
Anafi_df = pd.read_csv('2020_04_16_Anifi.csv')
Anafi_df = pd.DataFrame.from_dict(OrderedDict(Anafi_df))

In [4]:
Anafi_df

,Date/Time,time,battery_level,controller_gps_latitude,controller_gps_longitude,flying_state,alert_state,wifi_signal,product_gps_available,product_gps_longitude,...,speed_vx,speed_vy,speed_vz,angle_phi,angle_theta,angle_psi,altitude,flip_type,speed,Dist to RC
0,57:01.0,6,93,36.586979,126.375217,7,0,-36,True,126.375218,...,0.0,0.0,0.0,0.032337,0.099089,1.915989,0.0,0,0.0,0.0
1,57:01.2,205,93,36.586979,126.375217,7,0,-36,True,126.375218,...,0.0,0.0,0.0,0.032389,0.099151,1.915991,0.0,0,0.0,0.0
2,57:01.4,398,93,36.586979,126.375217,7,0,-36,True,126.375218,...,0.0,0.0,0.0,0.032389,0.099151,1.915991,0.0,0,0.0,0.0
3,57:01.4,398,93,36.586979,126.375217,7,0,-36,True,126.375218,...,0.0,0.0,0.0,0.032389,0.099151,1.915991,0.0,0,0.0,0.0
4,57:01.4,405,93,36.586979,126.375217,7,0,-36,True,126.375218,...,0.0,0.0,0.0,0.032412,0.099243,1.916087,0.0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8501,12:42.0,941019,35,36.586981,126.375217,0,0,-37,True,126.375225,...,0.0,0.0,0.0,-0.001943,0.095879,-0.680788,0.0,0,0.0,1.0
8502,12:42.1,941119,35,36.586981,126.375217,0,0,-27,True,126.375225,...,0.0,0.0,0.0,-0.001943,0.095879,-0.680788,0.0,0,0.0,1.0
8503,12:42.2,941205,35,36.586981,126.375217,0,0,-27,True,126.375225,...,0.0,0.0,0.0,-0.002024,0.096170,-0.683416,0.0,0,0.0,1.0
8504,12:42.4,941405,35,36.586981,126.375217,0,0,-27,True,126.375224,...,0.0,0.0,0.0,-0.002040,0.096333,-0.685360,0.0,0,0.0,1.0
8505,12:42.6,941554,35,36.586981,126.375217,0,0,-27,True,126.375224,...,0.0,0.0,0.0,-0.002269,0.096549,-0.686376,0.0,0,0.0,0.9

In [5]:
#Anafi_df = Anafi_df.drop(index=0, axis=0)

In [6]:
Anafi_df['Date/Time']

0       57:01.0
1       57:01.2
2       57:01.4
3       57:01.4
4       57:01.4
         ...
8501    12:42.0
8502    12:42.1
8503    12:42.2
8504    12:42.4
8505    12:42.6
Name: Date/Time, Length: 8506, dtype: object

In [7]:
#Anafi_df['Edit_Date/Time'] = Anafi_df.apply(lambda x : "2020-04-16".format(x))

In [8]:
Anafi_df

,Date/Time,time,battery_level,controller_gps_latitude,controller_gps_longitude,flying_state,alert_state,wifi_signal,product_gps_available,product_gps_longitude,...,speed_vx,speed_vy,speed_vz,angle_phi,angle_theta,angle_psi,altitude,flip_type,speed,Dist to RC
0,57:01.0,6,93,36.586979,126.375217,7,0,-36,True,126.375218,...,0.0,0.0,0.0,0.032337,0.099089,1.915989,0.0,0,0.0,0.0
1,57:01.2,205,93,36.586979,126.375217,7,0,-36,True,126.375218,...,0.0,0.0,0.0,0.032389,0.099151,1.915991,0.0,0,0.0,0.0
2,57:01.4,398,93,36.586979,126.375217,7,0,-36,True,126.375218,...,0.0,0.0,0.0,0.032389,0.099151,1.915991,0.0,0,0.0,0.0
3,57:01.4,398,93,36.586979,126.375217,7,0,-36,True,126.375218,...,0.0,0.0,0.0,0.032389,0.099151,1.915991,0.0,0,0.0,0.0
4,57:01.4,405,93,36.586979,126.375217,7,0,-36,True,126.375218,...,0.0,0.0,0.0,0.032412,0.099243,1.916087,0.0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8501,12:42.0,941019,35,36.586981,126.375217,0,0,-37,True,126.375225,...,0.0,0.0,0.0,-0.001943,0.095879,-0.680788,0.0,0,0.0,1.0
8502,12:42.1,941119,35,36.586981,126.375217,0,0,-27,True,126.375225,...,0.0,0.0,0.0,-0.001943,0.095879,-0.680788,0.0,0,0.0,1.0
8503,12:42.2,941205,35,36.586981,126.375217,0,0,-27,True,126.375225,...,0.0,0.0,0.0,-0.002024,0.096170,-0.683416,0.0,0,0.0,1.0
8504,12:42.4,941405,35,36.586981,126.375217,0,0,-27,True,126.375224,...,0.0,0.0,0.0,-0.002040,0.096333,-0.685360,0.0,0,0.0,1.0
8505,12:42.6,941554,35,36.586981,126.375217,0,0,-27,True,126.375224,...,0.0,0.0,0.0,-0.002269,0.096549,-0.686376,0.0,0,0.0,0.9

In [9]:
print(Anafi_df['Date/Time'].dtype)

object

In [47]:
Anafi_df['FlightTime'] = pd.to_datetime(Anafi_df['Date/Time'], format = "%M:%S.%f")

In [48]:
print(Anafi_df['FlightTime'].dtype)

datetime64[ns]

In [49]:
AnafiFirst_df = Anafi_df.iloc[:1527,:]
AnafiSecond_df = Anafi_df.iloc[1527:,:]

In [13]:
AnafiFirst_df.tail

<bound method NDFrame.tail of      Date/Time    time  battery_level  controller_gps_latitude  \
0      57:01.0       6             93                36.586979
1      57:01.2     205             93                36.586979
2      57:01.4     398             93                36.586979
3      57:01.4     398             93                36.586979
4      57:01.4     405             93                36.586979
...        ...     ...            ...                      ...
1522   59:59.4  178405             82                36.586981
1523   59:59.6  178605             82                36.586981
1524   59:59.8  178805             82                36.586981
1525   59:59.8  178841             82                36.586981
1526   59:59.8  178841             82                36.586981

      controller_gps_longitude  flying_state  alert_state  wifi_signal  \
0                   126.375217             7            0          -36
1                   126.375217             7            0          -36
2                   126.375217             7            0          -36
3                   126.375217             7            0          -36
4                   126.375217             7            0          -36
...                        ...           ...          ...          ...
1522                126.375217             2            0          -53
1523                126.375217             2            0          -53
1524                126.375217             2            0          -53
1525                126.375217             2            0          -53
1526                126.375217             2            0          -53

      product_gps_available  product_gps_longitude  ...  speed_vy  speed_vz  \
0                      True             126.375218  ...  0.000000  0.000000
1                      True             126.375218  ...  0.000000  0.000000
2                      True             126.375218  ...  0.000000  0.000000
3                      True             126.375218  ...  0.000000  0.000000
4                      True             126.375218  ...  0.000000  0.000000
...                     ...                    ...  ...       ...       ...
1522                   True             126.374626  ...  0.017778 -0.005790
1523                   True             126.374626  ... -0.009454  0.015187
1524                   True             126.374626  ... -0.031540  0.039798
1525                   True             126.374626  ... -0.031540  0.039798
1526                   True             126.374626  ... -0.031540  0.039798

      angle_phi  angle_theta  angle_psi  altitude  flip_type     speed  \
0      0.032337     0.099089   1.915989  0.000000          0  0.000000
1      0.032389     0.099151   1.915991  0.000000          0  0.000000
2      0.032389     0.099151   1.915991  0.000000          0  0.000000
3      0.032389     0.099151   1.915991  0.000000          0  0.000000
4      0.032412     0.099243   1.916087  0.000000          0  0.000000
...         ...          ...        ...       ...        ...       ...
1522  -0.041865    -0.027612  -0.683205  9.348801          0  0.064304
1523  -0.034716    -0.055444  -0.682943  9.358860          0  0.077338
1524  -0.015510    -0.045008  -0.684066  9.359352          0  0.068246
1525  -0.015510    -0.045008  -0.684066  9.359352          0  0.068246
1526  -0.015510    -0.045008  -0.684066  9.359352          0  0.068246

      Dist to RC              FlightTime
0            0.0 1900-01-01 00:57:01.000
1            0.0 1900-01-01 00:57:01.200
2            0.0 1900-01-01 00:57:01.400
3            0.0 1900-01-01 00:57:01.400
4            0.0 1900-01-01 00:57:01.400
...          ...                     ...
1522        64.4 1900-01-01 00:59:59.400
1523        64.4 1900-01-01 00:59:59.600
1524        64.4 1900-01-01 00:59:59.800
1525        64.4 1900-01-01 00:59:59.800
1526        64.4 1900-01-01 00:59:59.800

[1527 rows x 24 columns]>

In [14]:
AnafiSecond_df.head

<bound method NDFrame.head of      Date/Time    time  battery_level  controller_gps_latitude  \
1527   00:00.0  179005             82                36.586981
1528   00:00.1  179119             82                36.586981
1529   00:00.2  179205             82                36.586981
1530   00:00.4  179376             82                36.586981
1531   00:00.4  179405             82                36.586981
...        ...     ...            ...                      ...
8501   12:42.0  941019             35                36.586981
8502   12:42.1  941119             35                36.586981
8503   12:42.2  941205             35                36.586981
8504   12:42.4  941405             35                36.586981
8505   12:42.6  941554             35                36.586981

      controller_gps_longitude  flying_state  alert_state  wifi_signal  \
1527                126.375217             2            0          -53
1528                126.375217             2            0          -54
1529                126.375217             2            0          -54
1530                126.375217             2            0          -54
1531                126.375217             2            0          -54
...                        ...           ...          ...          ...
8501                126.375217             0            0          -37
8502                126.375217             0            0          -27
8503                126.375217             0            0          -27
8504                126.375217             0            0          -27
8505                126.375217             0            0          -27

      product_gps_available  product_gps_longitude  ...  speed_vy  speed_vz  \
1527                   True             126.374626  ... -0.004746  0.041686
1528                   True             126.374626  ... -0.004746  0.041686
1529                   True             126.374626  ...  0.008032  0.049474
1530                   True             126.374626  ...  0.008032  0.049474
1531                   True             126.374626  ... -0.017266  0.035914
...                     ...                    ...  ...       ...       ...
8501                   True             126.375225  ...  0.000000  0.000000
8502                   True             126.375225  ...  0.000000  0.000000
8503                   True             126.375225  ...  0.000000  0.000000
8504                   True             126.375224  ...  0.000000  0.000000
8505                   True             126.375224  ...  0.000000  0.000000

      angle_phi  angle_theta  angle_psi  altitude  flip_type     speed  \
1527  -0.012426    -0.040865  -0.683060  9.362684          0  0.043502
1528  -0.012426    -0.040865  -0.683060  9.362684          0  0.043502
1529  -0.033565    -0.045781  -0.682283  9.356401          0  0.054969
1530  -0.033565    -0.045781  -0.682283  9.356401          0  0.054969
1531  -0.048154    -0.029660  -0.681637  9.360655          0  0.041098
...         ...          ...        ...       ...        ...       ...
8501  -0.001943     0.095879  -0.680788  0.000000          0  0.000000
8502  -0.001943     0.095879  -0.680788  0.000000          0  0.000000
8503  -0.002024     0.096170  -0.683416  0.000000          0  0.000000
8504  -0.002040     0.096333  -0.685360  0.000000          0  0.000000
8505  -0.002269     0.096549  -0.686376  0.000000          0  0.000000

      Dist to RC              FlightTime
1527        64.4 1900-01-01 00:00:00.000
1528        64.4 1900-01-01 00:00:00.100
1529        64.4 1900-01-01 00:00:00.200
1530        64.4 1900-01-01 00:00:00.400
1531        64.4 1900-01-01 00:00:00.400
...          ...                     ...
8501         1.0 1900-01-01 00:12:42.000
8502         1.0 1900-01-01 00:12:42.100
8503         1.0 1900-01-01 00:12:42.200
8504         1.0 1900-01-01 00:12:42.400
8505         0.9 1900-01-01 00:12:42.600

[6979 rows x 24 columns]>

In [15]:
AnafiFirst_df['FlightTimeEdit']=AnafiFirst_df['FlightTime'].apply(lambda x:x.replace(year = 2020, month = 4, day=16, hour = 10))

<ipython-input-15-59379e9d3158>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  AnafiFirst_df['FlightTimeEdit']=AnafiFirst_df['FlightTime'].apply(lambda x:x.replace(year = 2020, month = 4, day=16, hour = 10))

In [16]:
print(AnafiFirst_df['FlightTimeEdit'].dtype)

datetime64[ns]

In [17]:
AnafiFirst_df['FlightTimeEdit']

0      2020-04-16 10:57:01.000
1      2020-04-16 10:57:01.200
2      2020-04-16 10:57:01.400
3      2020-04-16 10:57:01.400
4      2020-04-16 10:57:01.400
                 ...
1522   2020-04-16 10:59:59.400
1523   2020-04-16 10:59:59.600
1524   2020-04-16 10:59:59.800
1525   2020-04-16 10:59:59.800
1526   2020-04-16 10:59:59.800
Name: FlightTimeEdit, Length: 1527, dtype: datetime64[ns]

In [18]:
AnafiSecond_df['FlightTimeEdit']=AnafiSecond_df['FlightTime'].apply(lambda x:x.replace(year = 2020, month = 4, day=16, hour = 11))

<ipython-input-18-d770aaa8d2b9>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  AnafiSecond_df['FlightTimeEdit']=AnafiSecond_df['FlightTime'].apply(lambda x:x.replace(year = 2020, month = 4, day=16, hour = 11))

In [19]:
AnafiSecond_df['FlightTimeEdit']

1527   2020-04-16 11:00:00.000
1528   2020-04-16 11:00:00.100
1529   2020-04-16 11:00:00.200
1530   2020-04-16 11:00:00.400
1531   2020-04-16 11:00:00.400
                 ...
8501   2020-04-16 11:12:42.000
8502   2020-04-16 11:12:42.100
8503   2020-04-16 11:12:42.200
8504   2020-04-16 11:12:42.400
8505   2020-04-16 11:12:42.600
Name: FlightTimeEdit, Length: 6979, dtype: datetime64[ns]

In [20]:
AnafiNew_df = pd.concat([AnafiFirst_df, AnafiSecond_df])

In [21]:
AnafiNew_df

,Date/Time,time,battery_level,controller_gps_latitude,controller_gps_longitude,flying_state,alert_state,wifi_signal,product_gps_available,product_gps_longitude,...,speed_vz,angle_phi,angle_theta,angle_psi,altitude,flip_type,speed,Dist to RC,FlightTime,FlightTimeEdit
0,57:01.0,6,93,36.586979,126.375217,7,0,-36,True,126.375218,...,0.0,0.032337,0.099089,1.915989,0.0,0,0.0,0.0,1900-01-01 00:57:01.000,2020-04-16 10:57:01.000
1,57:01.2,205,93,36.586979,126.375217,7,0,-36,True,126.375218,...,0.0,0.032389,0.099151,1.915991,0.0,0,0.0,0.0,1900-01-01 00:57:01.200,2020-04-16 10:57:01.200
2,57:01.4,398,93,36.586979,126.375217,7,0,-36,True,126.375218,...,0.0,0.032389,0.099151,1.915991,0.0,0,0.0,0.0,1900-01-01 00:57:01.400,2020-04-16 10:57:01.400
3,57:01.4,398,93,36.586979,126.375217,7,0,-36,True,126.375218,...,0.0,0.032389,0.099151,1.915991,0.0,0,0.0,0.0,1900-01-01 00:57:01.400,2020-04-16 10:57:01.400
4,57:01.4,405,93,36.586979,126.375217,7,0,-36,True,126.375218,...,0.0,0.032412,0.099243,1.916087,0.0,0,0.0,0.0,1900-01-01 00:57:01.400,2020-04-16 10:57:01.400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8501,12:42.0,941019,35,36.586981,126.375217,0,0,-37,True,126.375225,...,0.0,-0.001943,0.095879,-0.680788,0.0,0,0.0,1.0,1900-01-01 00:12:42.000,2020-04-16 11:12:42.000
8502,12:42.1,941119,35,36.586981,126.375217,0,0,-27,True,126.375225,...,0.0,-0.001943,0.095879,-0.680788,0.0,0,0.0,1.0,1900-01-01 00:12:42.100,2020-04-16 11:12:42.100
8503,12:42.2,941205,35,36.586981,126.375217,0,0,-27,True,126.375225,...,0.0,-0.002024,0.096170,-0.683416,0.0,0,0.0,1.0,1900-01-01 00:12:42.200,2020-04-16 11:12:42.200
8504,12:42.4,941405,35,36.586981,126.375217,0,0,-27,True,126.375224,...,0.0,-0.002040,0.096333,-0.685360,0.0,0,0.0,1.0,1900-01-01 00:12:42.400,2020-04-16 11:12:42.400
8505,12:42.6,941554,35,36.586981,126.375217,0,0,-27,True,126.375224,...,0.0,-0.002269,0.096549,-0.686376,0.0,0,0.0,0.9,1900-01-01 00:12:42.600,2020-04-16 11:12:42.600

In [52]:
Time_Ser =AnafiNew_df.groupby('FlightTimeEdit', sort = False)['FlightTimeEdit'].min()

# Problem description
# DataFrame.groupby() has a parameter that selects whether the result should be sorted by groups.

# However, if the DataFrame has a multi-index and the grouping is only done by one index, the result is sorted regardless of the value of sort.
# Grouping by more than one index works.
# Passing the single index as a list [0] does not fix the problem.

In [51]:
Time_Ser

FlightTimeEdit
2020-04-16 10:57:01.000   2020-04-16 10:57:01.000
2020-04-16 10:57:01.200   2020-04-16 10:57:01.200
2020-04-16 10:57:01.400   2020-04-16 10:57:01.400
2020-04-16 10:57:01.600   2020-04-16 10:57:01.600
2020-04-16 10:57:01.800   2020-04-16 10:57:01.800
                                    ...
2020-04-16 11:12:42.000   2020-04-16 11:12:42.000
2020-04-16 11:12:42.100   2020-04-16 11:12:42.100
2020-04-16 11:12:42.200   2020-04-16 11:12:42.200
2020-04-16 11:12:42.400   2020-04-16 11:12:42.400
2020-04-16 11:12:42.600   2020-04-16 11:12:42.600
Name: FlightTimeEdit, Length: 6127, dtype: datetime64[ns]

In [24]:
print(Time_Ser.dtype)

datetime64[ns]

In [25]:
battery_level =AnafiNew_df.groupby('FlightTimeEdit', 
                                   sort = False)['battery_level'].max()

In [26]:
print(battery_level)

FlightTimeEdit
2020-04-16 10:57:01.000    93
2020-04-16 10:57:01.200    93
2020-04-16 10:57:01.400    93
2020-04-16 10:57:01.600    93
2020-04-16 10:57:01.800    93
                           ..
2020-04-16 11:12:42.000    35
2020-04-16 11:12:42.100    35
2020-04-16 11:12:42.200    35
2020-04-16 11:12:42.400    35
2020-04-16 11:12:42.600    35
Name: battery_level, Length: 6127, dtype: int64

In [27]:
AnafiNew_df.columns

Index(['Date/Time', 'time', 'battery_level', 'controller_gps_latitude',
       'controller_gps_longitude', 'flying_state', 'alert_state',
       'wifi_signal', 'product_gps_available', 'product_gps_longitude',
       'product_gps_latitude', 'product_gps_position_error',
       'product_gps_sv_number', 'speed_vx', 'speed_vy', 'speed_vz',
       'angle_phi', 'angle_theta', 'angle_psi', 'altitude', 'flip_type',
       'speed', 'Dist to RC', 'FlightTime', 'FlightTimeEdit'],
      dtype='object')

In [28]:
lat_Ser =AnafiNew_df.groupby('FlightTimeEdit', 
                             sort = False)['product_gps_latitude'].max()

In [29]:
print(lat_Ser)

FlightTimeEdit
2020-04-16 10:57:01.000    36.586979
2020-04-16 10:57:01.200    36.586979
2020-04-16 10:57:01.400    36.586979
2020-04-16 10:57:01.600    36.586979
2020-04-16 10:57:01.800    36.586979
                             ...
2020-04-16 11:12:42.000    36.586988
2020-04-16 11:12:42.100    36.586988
2020-04-16 11:12:42.200    36.586988
2020-04-16 11:12:42.400    36.586988
2020-04-16 11:12:42.600    36.586988
Name: product_gps_latitude, Length: 6127, dtype: float64

In [30]:
type(lat_Ser)

pandas.core.series.Series

In [31]:
lon_Ser =AnafiNew_df.groupby('FlightTimeEdit', 
                             sort = False)['product_gps_longitude'].mean()

In [32]:
type(lat_Ser)

pandas.core.series.Series

In [33]:
alt_Ser =AnafiNew_df.groupby('FlightTimeEdit', sort = False)['altitude'].mean()

In [34]:
lat_Ser

FlightTimeEdit
2020-04-16 10:57:01.000    36.586979
2020-04-16 10:57:01.200    36.586979
2020-04-16 10:57:01.400    36.586979
2020-04-16 10:57:01.600    36.586979
2020-04-16 10:57:01.800    36.586979
                             ...
2020-04-16 11:12:42.000    36.586988
2020-04-16 11:12:42.100    36.586988
2020-04-16 11:12:42.200    36.586988
2020-04-16 11:12:42.400    36.586988
2020-04-16 11:12:42.600    36.586988
Name: product_gps_latitude, Length: 6127, dtype: float64

In [35]:
alt_Ser

FlightTimeEdit
2020-04-16 10:57:01.000    0.0
2020-04-16 10:57:01.200    0.0
2020-04-16 10:57:01.400    0.0
2020-04-16 10:57:01.600    0.0
2020-04-16 10:57:01.800    0.0
                          ...
2020-04-16 11:12:42.000    0.0
2020-04-16 11:12:42.100    0.0
2020-04-16 11:12:42.200    0.0
2020-04-16 11:12:42.400    0.0
2020-04-16 11:12:42.600    0.0
Name: altitude, Length: 6127, dtype: float64

In [36]:
AnafiNew_df['altitude'].dtypes

dtype('float64')

In [37]:
wifi_signal =AnafiNew_df.groupby('FlightTimeEdit', 
                                 sort = False)['wifi_signal'].min()

In [38]:
speed_vx =AnafiNew_df.groupby('FlightTimeEdit', 
                              sort = False)['speed_vx'].mean()

In [39]:
speed_vy =AnafiNew_df.groupby('FlightTimeEdit', 
                              sort = False)['speed_vy'].mean()

In [40]:
speed_vz =AnafiNew_df.groupby('FlightTimeEdit', 
                              sort = False)['speed_vz'].mean()

In [41]:
speed =AnafiNew_df.groupby('FlightTimeEdit', 
                           sort = False)['speed'].mean()

In [42]:
AnafiNew_df.dtypes

Date/Time                             object
time                                   int64
battery_level                          int64
controller_gps_latitude              float64
controller_gps_longitude             float64
flying_state                           int64
alert_state                            int64
wifi_signal                            int64
product_gps_available                   bool
product_gps_longitude                float64
product_gps_latitude                 float64
product_gps_position_error             int64
product_gps_sv_number                  int64
speed_vx                             float64
speed_vy                             float64
speed_vz                             float64
angle_phi                            float64
angle_theta                          float64
angle_psi                            float64
altitude                             float64
flip_type                              int64
speed                                float64
Dist to RC                           float64
FlightTime                    datetime64[ns]
FlightTimeEdit                datetime64[ns]
dtype: object

In [43]:
# battery level 작업을 위한 전처리
AnafiDateSet=list(zip(Time_Ser, battery_level, lat_Ser, lon_Ser, alt_Ser,
                      wifi_signal, speed_vx, speed_vy, speed_vz, speed ))

df=pd.DataFrame(data=AnafiDateSet, columns=['FlightTimeEdit', 'battery_level', 
                                        'product_gps_latitude','product_gps_longitude', 
                                        'altitude', 'wifi_signal',
                                        'speed_vx', 'speed_vy', 'speed_vz', 'speed'])

In [44]:
df

,FlightTimeEdit,battery_level,product_gps_latitude,product_gps_longitude,altitude,wifi_signal,speed_vx,speed_vy,speed_vz,speed
0,2020-04-16 10:57:01.000,93,36.586979,126.375218,0.0,-36,0.0,0.0,0.0,0.0
1,2020-04-16 10:57:01.200,93,36.586979,126.375218,0.0,-36,0.0,0.0,0.0,0.0
2,2020-04-16 10:57:01.400,93,36.586979,126.375218,0.0,-36,0.0,0.0,0.0,0.0
3,2020-04-16 10:57:01.600,93,36.586979,126.375218,0.0,-36,0.0,0.0,0.0,0.0
4,2020-04-16 10:57:01.800,93,36.586979,126.375218,0.0,-36,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
6122,2020-04-16 11:12:42.000,35,36.586988,126.375225,0.0,-37,0.0,0.0,0.0,0.0
6123,2020-04-16 11:12:42.100,35,36.586988,126.375225,0.0,-27,0.0,0.0,0.0,0.0
6124,2020-04-16 11:12:42.200,35,36.586988,126.375225,0.0,-27,0.0,0.0,0.0,0.0
6125,2020-04-16 11:12:42.400,35,36.586988,126.375224,0.0,-27,0.0,0.0,0.0,0.0
6126,2020-04-16 11:12:42.600,35,36.586988,126.375224,0.0,-27,0.0,0.0,0.0,0.0

In [45]:
df.to_csv('2020_04_16_Anifi_edited.csv')